package com.earl.cas.entity;
// Generated 2016-11-21 9:28:51 by Hibernate Tools 5.2.0.Beta1

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;

import com.earl.cas.commons.domain.IdAnnotatioin;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Album generated by hbm2java
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
//jackson 控制，放回字段为null,将被过滤
@Entity
@Table(name = "album", catalog = "clubsystem")
public class Album implements Serializable
{
	private static final long serialVersionUID = 1L;
	
	@IdAnnotatioin //用于动态更新数据
	private Integer id;
	
	//社团
	private Integer clubId;
	
	//相册名称
	private String name;
	
	//创建时间
	private String createtime;
	
	//相册封面路径
	private String path;
	
	//社团名称
	private String ClubName;
	
	//相册照片总数
	private Long PhotoNumber;
	
	public Album() {
	}

	public Album(Integer id, String createtime) {
		this.id = id;
		this.createtime = createtime;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "club_id")
	public Integer getClubId() {
		return clubId;
	}

	public void setClubId(Integer clubId) {
		this.clubId = clubId;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Generated(GenerationTime.INSERT)
	@Column(name = "createtime")
	public String getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(String createtime) {
		this.createtime = createtime;
	}

	@Column(name = "path")
	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}
	
	@Transient
	public String getClubName() {
		return ClubName;
	}

	public void setClubName(String clubName) {
		ClubName = clubName;
	}
	
	@Transient
	public Long getPhotoNumber() {
		return PhotoNumber;
	}

	public void setPhotoNumber(Long photoNumber) {
		PhotoNumber = photoNumber;
	}

	@Override
	public String toString() {
		return "Album [id=" + id + ", clubId=" + clubId + ", name=" + name
				+ ", createtime=" + createtime + ", path=" + path
				+ ", ClubName=" + ClubName + "]";
	}
}
