package com.earl.cas.entity;
// Generated 2016-11-21 9:28:51 by Hibernate Tools 5.2.0.Beta1

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;

import com.earl.cas.commons.domain.IdAnnotatioin;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Apply generated by hbm2java
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
//jackson 控制，放回字段为null,将被过滤
@Entity
@Table(name = "apply", catalog = "clubsystem")
public class Apply implements Serializable
{
	//表明类的不同版本间的兼容性
	private static final long serialVersionUID = 1L;
	
	//申请表编号
	@IdAnnotatioin //用于动态更新数据
	private int id;
	
	//社团id
	private Integer clubId;
	
	//用户
	private Integer detailId;
	
	//真实姓名
	private String name;
	
	//邮箱
	private String email;
	
	//性别
	private Boolean sex;
	
	//年龄
	private Integer age;
	
	//民族
	private String nation;
	
	//爱好
	private String hobby;
	
	//电话
	private String phone;
	
	//专业班级
	private String majorClass;
	
	//个人简介
	private String introduce;
	
	//申请时间
	private String createtime;
	
	//申请理由
	private String reason;
	
	//状态
	private Integer statue;

	public Apply() {
	}

	public Apply(int id, String createtime) {
		this.id = id;
		this.createtime = createtime;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "club_id")
	public Integer getClubId() {
		return clubId;
	}

	public void setClubId(Integer clubId) {
		this.clubId = clubId;
	}
	
	@Column(name = "detail_id")
	public Integer getDetailId() {
		return detailId;
	}

	public void setDetailId(Integer detailId) {
		this.detailId = detailId;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "sex")
	public Boolean getSex() {
		return this.sex;
	}

	public void setSex(Boolean sex) {
		this.sex = sex;
	}

	@Column(name = "age")
	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	@Column(name = "nation")
	public String getNation() {
		return this.nation;
	}

	public void setNation(String nation) {
		this.nation = nation;
	}

	@Column(name = "hobby")
	public String getHobby() {
		return this.hobby;
	}

	public void setHobby(String hobby) {
		this.hobby = hobby;
	}

	@Column(name = "phone")
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "major_class")
	public String getMajorClass() {
		return this.majorClass;
	}

	public void setMajorClass(String majorClass) {
		this.majorClass = majorClass;
	}

	@Column(name = "introduce", length = 65535)
	public String getIntroduce() {
		return this.introduce;
	}

	public void setIntroduce(String introduce) {
		this.introduce = introduce;
	}

	@Generated(GenerationTime.INSERT)
	@Column(name = "createtime")
	public String getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(String createtime) {
		this.createtime = createtime;
	}

	@Column(name = "reason", length = 65535)
	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	@Column(name = "statue")
	public Integer getStatue() {
		return this.statue;
	}

	public void setStatue(Integer statue) {
		this.statue = statue;
	}

	@Override
	public String toString() {
		return "Apply [id=" + id + ", clubId=" + clubId + ", detailId="
				+ detailId + ", name=" + name + ", email=" + email + ", sex="
				+ sex + ", age=" + age + ", nation=" + nation + ", hobby="
				+ hobby + ", phone=" + phone + ", majorClass=" + majorClass
				+ ", introduce=" + introduce + ", createtime=" + createtime
				+ ", reason=" + reason + ", statue=" + statue + "]";
	}

}
