package com.earl.cas.entity;
// Generated 2016-11-21 9:28:51 by Hibernate Tools 5.2.0.Beta1

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;

/**
 * ClubType generated by hbm2java
 */
@Entity
@Table(name = "club_type", catalog = "clubsystem")
public class ClubType implements Serializable
{
	private static final long serialVersionUID = 1L;
	
	//类型编号
	private int id;
	
	//类型名称
	private String name;
	
	//创建时间
	private String createtime;
	

	public ClubType() {
	}

	public ClubType(int id, String createtime) {
		this.id = id;
		this.createtime = createtime;
	}


	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Generated(GenerationTime.INSERT)
	@Column(name = "createtime")
	public String getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(String createtime) {
		this.createtime = createtime;
	}

	@Override
	public String toString() {
		return "ClubType [id=" + id + ", name=" + name + ", createtime="
				+ createtime + "]";
	}
}
