package com.earl.cas.entity;
// Generated 2016-11-21 9:28:51 by Hibernate Tools 5.2.0.Beta1

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;

import com.earl.cas.commons.domain.IdAnnotatioin;

/**
 * Message generated by hbm2java
 */
@Entity
@Table(name = "message", catalog = "clubsystem")
public class Message implements Serializable
{
	private static final long serialVersionUID = 1L;
	
	//留言编号
	@IdAnnotatioin //用于动态更新数据
	private int id;
	
	//父级id
	private Integer fatherId;
	
	//用户id
	private Integer detailId;
	
	//留言内容
	private String content;
	
	//创建时间
	private String createtime;
	
	//点赞次数
	private Integer good;
	
	//点踩次数
	private Integer bad;
	
	public Message() {
	}

	public Message(int id, String createtime) {
		this.id = id;
		this.createtime = createtime;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "father_id")
	public Integer getFatherId() {
		return fatherId;
	}

	public void setFatherId(Integer fatherId) {
		this.fatherId = fatherId;
	}

	@Column(name = "detail_id")
	public Integer getDetailId() {
		return detailId;
	}

	public void setDetailId(Integer detailId) {
		this.detailId = detailId;
	}

	@Column(name = "content", length = 65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Generated(GenerationTime.INSERT)
	@Column(name = "createtime")
	public String getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(String createtime) {
		this.createtime = createtime;
	}

	@Column(name = "good")
	public Integer getGood() {
		return this.good;
	}

	public void setGood(Integer good) {
		this.good = good;
	}

	@Column(name = "bad")
	public Integer getBad() {
		return this.bad;
	}

	public void setBad(Integer bad) {
		this.bad = bad;
	}

	@Override
	public String toString() {
		return "Message [id=" + id + ", fatherId=" + fatherId + ", detailId="
				+ detailId + ", content=" + content + ", createtime="
				+ createtime + ", good=" + good + ", bad=" + bad + "]";
	}
}
