package com.earl.cas.entity;
// Generated 2016-11-21 9:28:51 by Hibernate Tools 5.2.0.Beta1

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Table;

import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;

import com.earl.cas.commons.domain.IdAnnotatioin;

/**
 * Photo generated by hbm2java
 */
@Entity
@Table(name = "photo", catalog = "clubsystem")
public class Photo implements Serializable
{
	private static final long serialVersionUID = 1L;
	
	@IdAnnotatioin //用于动态更新数据
	private int id;
	
	//相册
	private Integer albumId;
	
	//图片备注
	private String content;
	
	//图片路径
	private String path;
	
	//创建时间
	private String createtime;

	public Photo() {
	}

	public Photo(int id, String createtime) {
		this.id = id;
		this.createtime = createtime;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@JoinColumn(name = "album_id")
	public Integer getAlbumId() {
		return albumId;
	}

	public void setAlbumId(Integer albumId) {
		this.albumId = albumId;
	}

	@Column(name = "content")
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "path")
	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	@Generated(GenerationTime.INSERT)
	@Column(name = "createtime")
	public String getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(String createtime) {
		this.createtime = createtime;
	}

	@Override
	public String toString() {
		return "Photo [id=" + id + ", albumId=" + albumId + ", content="
				+ content + ", path=" + path + ", createtime=" + createtime
				+ "]";
	}
}
